export interface Tights {
  name: string;
  category:string;
    MeasurementSPantsW1: string;
    MeasurementSPantsW2: string;
    MeasurementMPantsW1:string;
    MeasurementMPantsW2: string;
    MeasurementLPantsW1: string;
    MeasurementLPantsW2:string;
    MeasurementSHips1: string;
    MeasurementSHips2: string;
    MeasurementMHips1: string;
    MeasurementMHips2: string;
    MeasurementLHips1: string;
    MeasurementLHips2: string;
    MeasurementSLength1: string;
    MeasurementSLength2: string;
    MeasurementMLength1: string;
    MeasurementMLength2: string;
    MeasurementLLength1: string;
    MeasurementLLength2: string;
    MeasurementSCrotch1: string;
    MeasurementSCrotch2: string;
    MeasurementMCrotch1: string;
    MeasurementMCrotch2: string;
    MeasurementLCrotch1: string;
    MeasurementLCrotch2: string;
    MeasurementSThigh1: string;
    MeasurementSThigh2: string;
    MeasurementMThigh1: string;
    MeasurementMThigh2: string;
    MeasurementLThigh1: string;
    MeasurementLThigh2: string;
    MeasurementSKnee1: string;
    MeasurementSKnee2: string;
    MeasurementMKnee1: string;
    MeasurementMKnee2: string;
    MeasurementLKnee1: string;
    MeasurementLKnee2: string;
    MeasurementSQ: string;
    MeasurementMQ: string;
    MeasurementLQ: string;
    MeasurementSP: string;
    MeasurementMP: string;
    MeasurementLP: string;
  imgFront:string;
  imgBack:string;
  imgLeft:string;
  imgRight:string;
}
